query GetThreadsByTagName($tagName: String!) {
  threads_aggregate(where: {thread_tags: {tag: {name: {_eq: $tagName}}}}) {
    aggregate {
      count
    }
    nodes {
      id
      title
      author
      tweet_id
      thread_tags {
        tag {
          name
          id
        }
      }
    }
  }
}
